name: PR Agent
on:
  pull_request:
    types:
      - ready_for_review
      - opened
  issue_comment:
    types:
      - created
      - edited

jobs:
  pr_agent_job:
    if: ${{github.event.sender.type != 'Bot' && github.event.pull_request.draft == false}}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTION.AUTO_REVIEW: 'true'
          GITHUB_ACTION.AUTO_DESCRIBE: 'true'
          GITHUB_ACTION.AUTO_IMPROVE: 'false'
          PR_REVIEWER.EXTRA_INSTRUCTIONS: '必ず日本語で回答してください'
          PR_DESCRIPTION.PUBLISH_LABELS: 'false'
          PR_DESCRIPTION.PUBLISH_DESCRIPTION_AS_COMMENT: 'true'
          PR_DESCRIPTION.KEEP_ORIGINAL_USER_TITLE: 'false'
          PR_DESCRIPTION.ADD_ORIGINAL_USER_DESCRIPTION: 'false'
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: 'Please use Japanese in descriptions. Titles should have prefix of commitlint pattern such as `feat:`, `chore:`, `test:`, `fix:`, `ci:`, `docs:` etc'
